baseURL: https://networkpanic.github.io/aboutme
languageCode: en-us
title: "Martin Friedrich"
theme: "toha"

languages:
  en:
    languageName: English
    weight: 1

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

enableEmoji: true

# Site parameters
params:
  background: "images/bg.jpeg"
  logo:
    main: images/terminal.svg
    inverted: images/terminal_inverted.svg
    favicon: images/favicon.ico
  gitRepo: https://github.com/networkpanic/aboutme
  enableBlogPost: false
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: false